sudo: false
language: node_js
node_js:
  - "5"
cache:
  directories:
    - node_modules
env:
  global: MAINRUN=true
  matrix:
    - UNDERSCORE=1.4.4 BACKBONE=1.0
    - UNDERSCORE=1.5 BACKBONE=1.0
    - UNDERSCORE=1.7 BACKBONE=1.1
    - UNDERSCORE=1.7 BACKBONE=1.0
    - UNDERSCORE=1.6 BACKBONE=1.0
    - UNDERSCORE=1.4.4 BACKBONE=1.1.0
    - UNDERSCORE=1.5 BACKBONE=1.1
    - LODASH=2.4 BACKBONE=1.1
    - LODASH=3.0 BACKBONE=1.1
    - LODASH=3.1 BACKBONE=1.0
    - LODASH=3.10 BACKBONE=1.2
    - LODASH=4 BACKBONE=1.2
install:
  - ./ci.sh
after_success:
  - if [[ $MAINRUN == true ]]; then npm run-script coverage; fi
